<#
.SYNOPSIS
Bridge script for the Impeccable UI workflow.

.DESCRIPTION
This script reads Code/mine-flow-docs/architecture/07-ui-design-system.md and
extracts the design and product rules (e.g., ForUI direction, Tokens, components).
It then writes this extracted content into DESIGN.md and PRODUCT.md at the workspace root
to keep the Impeccable context synchronized with the canonical architecture docs, preventing drift.
#>

$ErrorActionPreference = "Stop"

$workspaceRoot = (Get-Item .).FullName
$designDocPath = Join-Path $workspaceRoot "Code\mine-flow-docs\architecture\07-ui-design-system.md"

if (-not (Test-Path $designDocPath)) {
    Write-Error "Could not find $designDocPath. Are you running this from the workspace root?"
}

Write-Host "Reading canonical design system from Code\mine-flow-docs\architecture\07-ui-design-system.md..."
$content = Get-Content $designDocPath -Raw

$designOutput = Join-Path $workspaceRoot "DESIGN.md"
$productOutput = Join-Path $workspaceRoot "PRODUCT.md"

Write-Host "Generating DESIGN.md..."
$designContent = @"
# DESIGN.md
> Auto-generated by Code/mine-flow-docs/scripts/impeccable-bridge.ps1
> Do not edit directly. Source of truth is architecture/07-ui-design-system.md.

$content
"@
Set-Content -Path $designOutput -Value $designContent -Encoding UTF8

Write-Host "Generating PRODUCT.md..."
$productContent = @"
# PRODUCT.md
> Auto-generated by Code/mine-flow-docs/scripts/impeccable-bridge.ps1
> Do not edit directly. Source of truth is architecture/07-ui-design-system.md.

$content
"@
Set-Content -Path $productOutput -Value $productContent -Encoding UTF8

Write-Host "Successfully generated DESIGN.md and PRODUCT.md at the workspace root."
Write-Host "Impeccable is now ready to run with the latest architectural context."
